import { bigint, boolean, index, integer, jsonb, pgTable, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";
import type { ServiceDeskAttachmentReference, ServiceDeskRequester } from "../../index.js";

export const catalogItems = pgTable("service_desk_catalog_items", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull(),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  status: text("status").notNull(),
  currentVersion: integer("current_version").notNull(),
  intakeMode: text("intake_mode").notNull(),
  formDefinitionId: uuid("form_definition_id"),
  workflowDefinitionId: uuid("workflow_definition_id"),
  approvalPolicyId: uuid("approval_policy_id"),
  defaultTicketType: text("default_ticket_type").notNull(),
  defaultPriority: text("default_priority").notNull(),
  categoryKey: text("category_key"),
  assignmentGroupId: text("assignment_group_id"),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
}, (table) => [index("service_desk_catalog_items_tenant_status_idx").on(table.tenantId, table.status, table.updatedAt)]);

export const catalogVersions = pgTable("service_desk_catalog_item_versions", {
  tenantId: uuid("tenant_id").notNull(),
  catalogItemId: uuid("catalog_item_id").notNull().references(() => catalogItems.id, { onDelete: "cascade" }),
  version: integer("version").notNull(),
  key: text("key").notNull(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  intakeMode: text("intake_mode").notNull(),
  formDefinitionId: uuid("form_definition_id"),
  workflowDefinitionId: uuid("workflow_definition_id"),
  approvalPolicyId: uuid("approval_policy_id"),
  defaultTicketType: text("default_ticket_type").notNull(),
  defaultPriority: text("default_priority").notNull(),
  categoryKey: text("category_key"),
  assignmentGroupId: text("assignment_group_id"),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  publishedAt: timestamp("published_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [
  primaryKey({ columns: [table.tenantId, table.catalogItemId, table.version] }),
  index("service_desk_catalog_versions_latest_idx").on(table.tenantId, table.catalogItemId, table.version),
]);

export const serviceDeskSlaPolicies = pgTable("service_desk_sla_policies", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  enabled: boolean("enabled").notNull().default(true),
  ticketTypes: jsonb("ticket_types").notNull().default([]),
  priorities: jsonb("priorities").notNull().default([]),
  categoryKeys: jsonb("category_keys").notNull().default([]),
  firstResponseMinutes: integer("first_response_minutes").notNull(),
  resolutionMinutes: integer("resolution_minutes").notNull(),
  pauseStatuses: jsonb("pause_statuses").notNull().default([]),
  escalationThresholds: jsonb("escalation_thresholds").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
}, (table) => [index("service_desk_sla_policies_tenant_idx").on(table.tenantId, table.enabled, table.updatedAt)]);

export const serviceDeskTickets = pgTable("service_desk_tickets", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull(),
  reference: text("reference").notNull(),
  type: text("type").notNull(),
  priority: text("priority").notNull(),
  status: text("status").notNull(),
  subject: text("subject").notNull(),
  description: text("description").notNull().default(""),
  categoryKey: text("category_key"),
  requester: jsonb("requester").$type<ServiceDeskRequester>().notNull().default({}),
  source: text("source").notNull(),
  assignmentGroupId: text("assignment_group_id"),
  assigneeUserId: uuid("assignee_user_id"),
  watcherUserIds: jsonb("watcher_user_ids").$type<string[]>().notNull().default([]),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  workflowInstanceId: uuid("workflow_instance_id"),
  approvalRequestId: uuid("approval_request_id"),
  slaPolicyId: uuid("sla_policy_id").references(() => serviceDeskSlaPolicies.id, { onDelete: "set null" }),
  firstResponseDueAt: timestamp("first_response_due_at", { withTimezone: true }),
  resolutionDueAt: timestamp("resolution_due_at", { withTimezone: true }),
  firstRespondedAt: timestamp("first_responded_at", { withTimezone: true }),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  pausedAt: timestamp("paused_at", { withTimezone: true }),
  accumulatedPausedMs: bigint("accumulated_paused_ms", { mode: "number" }).notNull().default(0),
  escalationLevel: integer("escalation_level").notNull().default(0),
  createdByUserId: uuid("created_by_user_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
}, (table) => [
  index("service_desk_tickets_tenant_status_idx").on(table.tenantId, table.status, table.updatedAt),
  index("service_desk_tickets_assignee_idx").on(table.tenantId, table.assigneeUserId, table.status, table.updatedAt),
]);

export const serviceDeskComments = pgTable("service_desk_comments", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull(),
  ticketId: uuid("ticket_id").notNull().references(() => serviceDeskTickets.id, { onDelete: "cascade" }),
  authorUserId: uuid("author_user_id").notNull(),
  visibility: text("visibility").notNull(),
  body: text("body").notNull().default(""),
  attachments: jsonb("attachments").$type<ServiceDeskAttachmentReference[]>().notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [index("service_desk_comments_ticket_idx").on(table.tenantId, table.ticketId, table.createdAt)]);

export const serviceDeskStatusEvents = pgTable("service_desk_status_events", {
  id: uuid("id").primaryKey(),
  tenantId: uuid("tenant_id").notNull(),
  ticketId: uuid("ticket_id").notNull().references(() => serviceDeskTickets.id, { onDelete: "cascade" }),
  fromStatus: text("from_status"),
  toStatus: text("to_status").notNull(),
  actorUserId: uuid("actor_user_id").notNull(),
  reason: text("reason").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [index("service_desk_status_events_ticket_idx").on(table.tenantId, table.ticketId, table.createdAt)]);
