import { randomUUID } from "node:crypto";
import type { AuditLog } from "@adminops/audit";
import { QueueConfiguration } from "./configuration.js";
import { QueueEntry } from "./entry.js";
import { QueueCapacityError, QueueConfigurationNotFoundError, QueueEntryNotFoundError, QueueStateError, QueueValidationError } from "./errors.js";
import type { QueueConfigurationRepository, QueueEntryRepository, QueueEventRepository } from "./repositories.js";
import type { AppointmentCheckInFacts, QueueCheckInSource, QueueConfigurationData, QueueCustomerReference, QueueEventType, QueuePriority } from "./types.js";

export class QueueService {
  constructor(private readonly configurations: QueueConfigurationRepository, private readonly entries: QueueEntryRepository, private readonly events: QueueEventRepository, private readonly auditLog?: AuditLog) {}
  async createConfiguration(input: { tenantId:string; actorUserId:string; id?:string; branchId:string; serviceId:string; departmentId?:string|null; prefix:string; averageServiceMinutes?:number; allowWalkIns?:boolean; allowAppointmentCheckIn?:boolean; maxEarlyCheckInMinutes?:number|null; maxLateCheckInMinutes?:number|null; maxConcurrentServing?:number }) {
    const id=input.id?.trim()||randomUUID(); if(await this.configurations.findById(input.tenantId,id)) throw new QueueValidationError(`Queue configuration '${id}' already exists`);
    if(await this.configurations.findForQueue(input.tenantId,input.branchId,input.serviceId,input.departmentId??null)) throw new QueueValidationError("A queue configuration already exists for this branch/service/department");
    let item:QueueConfiguration; try { item=QueueConfiguration.create({ id,tenantId:input.tenantId,branchId:input.branchId,serviceId:input.serviceId,departmentId:input.departmentId??null,prefix:input.prefix,averageServiceMinutes:input.averageServiceMinutes??10,allowWalkIns:input.allowWalkIns??true,allowAppointmentCheckIn:input.allowAppointmentCheckIn??true,maxEarlyCheckInMinutes:input.maxEarlyCheckInMinutes??60,maxLateCheckInMinutes:input.maxLateCheckInMinutes??30,maxConcurrentServing:input.maxConcurrentServing??1 }); } catch(error){ throw this.validation(error); }
    await this.configurations.save(item); await this.audit("queue.configuration_created",item.tenantId,input.actorUserId,"queue_configuration",item.id,{branchId:item.branchId,serviceId:item.serviceId}); return item;
  }
  async updateConfiguration(input:{tenantId:string;id:string;actorUserId:string}&Partial<Pick<QueueConfigurationData,"departmentId"|"prefix"|"averageServiceMinutes"|"allowWalkIns"|"allowAppointmentCheckIn"|"maxEarlyCheckInMinutes"|"maxLateCheckInMinutes"|"maxConcurrentServing">>) { const item=await this.requireConfiguration(input.tenantId,input.id); try{item.update(input);}catch(error){throw this.validation(error);} await this.configurations.save(item); await this.audit("queue.configuration_updated",item.tenantId,input.actorUserId,"queue_configuration",item.id,{}); return item; }
  listConfigurations(tenantId:string,branchId?:string){ return branchId?this.configurations.listByBranch(tenantId,branchId):this.configurations.listByTenant(tenantId); }
  getConfiguration(tenantId:string,id:string){ return this.requireConfiguration(tenantId,id); }
  async checkInWalkIn(input:{tenantId:string;branchId:string;serviceId:string;departmentId?:string|null;customer?:QueueCustomerReference;priority?:QueuePriority;priorityAdjustment?:number;source?:QueueCheckInSource;idempotencyKey?:string|null;metadata?:Record<string,unknown>;actorUserId?:string|null}) {
    if(input.idempotencyKey){const existing=await this.entries.findByIdempotencyKey(input.tenantId,input.idempotencyKey);if(existing)return existing;}
    const config=await this.requireQueueConfiguration(input.tenantId,input.branchId,input.serviceId,input.departmentId); if(!config.allowWalkIns) throw new QueueValidationError("Walk-in check-in is disabled for this queue");
    return this.createEntry({ ...input, config, kind:"WALK_IN", appointmentId:null, customer:input.customer??{} });
  }
  async checkInAppointment(input:{tenantId:string;appointment:AppointmentCheckInFacts;priority?:QueuePriority;priorityAdjustment?:number;source?:QueueCheckInSource;idempotencyKey?:string|null;metadata?:Record<string,unknown>;actorUserId?:string|null;now?:Date}) {
    if(input.idempotencyKey){const duplicate=await this.entries.findByIdempotencyKey(input.tenantId,input.idempotencyKey);if(duplicate)return duplicate;}
    const existing=await this.entries.findActiveByAppointment(input.tenantId,input.appointment.appointmentId); if(existing)return existing;
    const status=input.appointment.status?.toLowerCase(); if(status && ["cancelled","completed","no_show","noshow"].includes(status)) throw new QueueValidationError(`Appointment cannot be checked in from status '${input.appointment.status}'`);
    const config=await this.requireQueueConfiguration(input.tenantId,input.appointment.branchId,input.appointment.serviceId,input.appointment.departmentId); if(!config.allowAppointmentCheckIn) throw new QueueValidationError("Appointment check-in is disabled for this queue");
    const now=input.now??new Date(); if(input.appointment.startsAt){const start=input.appointment.startsAt.getTime(); if(config.maxEarlyCheckInMinutes!==null && now.getTime()<start-config.maxEarlyCheckInMinutes*60000) throw new QueueValidationError("Appointment is too early to check in"); if(config.maxLateCheckInMinutes!==null && now.getTime()>start+config.maxLateCheckInMinutes*60000) throw new QueueValidationError("Appointment is too late to check in");}
    return this.createEntry({ tenantId:input.tenantId,branchId:input.appointment.branchId,serviceId:input.appointment.serviceId,departmentId:input.appointment.departmentId??null,config,kind:"APPOINTMENT",appointmentId:input.appointment.appointmentId,customer:input.appointment.customer??{},priority:input.priority,priorityAdjustment:input.priorityAdjustment,source:input.source,idempotencyKey:input.idempotencyKey,metadata:input.metadata,actorUserId:input.actorUserId });
  }
  async getEntry(tenantId:string,id:string){return this.requireEntry(tenantId,id);}
  async getByPublicToken(tenantId:string,publicToken:string){const item=await this.entries.findByPublicToken(tenantId,publicToken);if(!item)throw new QueueEntryNotFoundError(publicToken);return item;}
  listQueue(tenantId:string,branchId:string,serviceId:string){return this.entries.listForQueue(tenantId,branchId,serviceId);}
  listBranch(tenantId:string,branchId:string){return this.entries.listByBranch(tenantId,branchId);}
  async callNext(input:{tenantId:string;branchId:string;serviceId:string;stationId:string;actorUserId:string}) { const config=await this.requireQueueConfiguration(input.tenantId,input.branchId,input.serviceId); const queue=await this.entries.listForQueue(input.tenantId,input.branchId,input.serviceId); const serving=queue.filter((item)=>item.status==="SERVING").length; if(serving>=config.maxConcurrentServing) throw new QueueCapacityError("Maximum concurrent serving capacity has been reached"); const next=queue.find((item)=>item.status==="WAITING"); if(!next) return null; try{next.call(input.stationId,input.actorUserId);}catch(error){throw new QueueStateError(error instanceof Error?error.message:"Could not call queue entry");} await this.entries.save(next); await this.event(next,"CALLED",input.actorUserId,{stationId:input.stationId}); return next; }
  async recall(input:{tenantId:string;id:string;actorUserId:string;stationId?:string|null}){const item=await this.requireEntry(input.tenantId,input.id);try{item.recall(input.stationId);}catch(error){throw this.state(error);}await this.entries.save(item);await this.event(item,"RECALLED",input.actorUserId,{stationId:item.stationId,recallCount:item.recallCount});return item;}
  async startService(input:{tenantId:string;id:string;actorUserId:string;stationId?:string|null}){const item=await this.requireEntry(input.tenantId,input.id);try{item.startService(input.actorUserId,input.stationId);}catch(error){throw this.state(error);}await this.entries.save(item);await this.event(item,"SERVICE_STARTED",input.actorUserId,{stationId:item.stationId});return item;}
  async complete(input:{tenantId:string;id:string;actorUserId:string}){const item=await this.requireEntry(input.tenantId,input.id);try{item.complete();}catch(error){throw this.state(error);}await this.entries.save(item);await this.event(item,"COMPLETED",input.actorUserId,{});return item;}
  async noShow(input:{tenantId:string;id:string;actorUserId:string}){const item=await this.requireEntry(input.tenantId,input.id);try{item.markNoShow();}catch(error){throw this.state(error);}await this.entries.save(item);await this.event(item,"NO_SHOW",input.actorUserId,{});return item;}
  async cancel(input:{tenantId:string;id:string;actorUserId:string|null;reason?:string}){const item=await this.requireEntry(input.tenantId,input.id);try{item.cancel();}catch(error){throw this.state(error);}await this.entries.save(item);await this.event(item,"CANCELLED",input.actorUserId,{reason:input.reason??null});return item;}
  async adjustPriority(input:{tenantId:string;id:string;actorUserId:string;priority:QueuePriority;adjustment?:number}){const item=await this.requireEntry(input.tenantId,input.id);try{item.adjustPriority(input.priority,input.adjustment??0);}catch(error){throw this.state(error);}await this.entries.save(item);await this.event(item,"PRIORITY_CHANGED",input.actorUserId,{priority:item.priority,adjustment:item.priorityAdjustment});return item;}
  async transfer(input:{tenantId:string;id:string;actorUserId:string;branchId:string;serviceId:string;departmentId?:string|null;stationId?:string|null}) { const from=await this.requireEntry(input.tenantId,input.id); const config=await this.requireQueueConfiguration(input.tenantId,input.branchId,input.serviceId,input.departmentId); try{from.markTransferred();}catch(error){throw this.state(error);} const ticket=await this.entries.nextTicketNumber(input.tenantId,input.branchId,input.serviceId,config.prefix,this.businessDate(new Date())); const now=new Date(); const to=new QueueEntry({id:randomUUID(),tenantId:input.tenantId,publicToken:randomUUID(),ticketNumber:ticket,kind:from.kind,branchId:input.branchId,serviceId:input.serviceId,departmentId:input.departmentId??null,appointmentId:from.appointmentId,customer:from.customer,priority:from.priority,priorityAdjustment:from.priorityAdjustment,priorityScore:from.priorityScore,checkInSource:"STAFF",status:"WAITING",stationId:null,servingStaffUserId:null,recallCount:0,checkedInAt:now,calledAt:null,serviceStartedAt:null,completedAt:null,noShowAt:null,cancelledAt:null,transferredAt:null,idempotencyKey:null,transferFromEntryId:from.id,metadata:{...from.metadata,transferredByUserId:input.actorUserId},createdAt:now,updatedAt:now}); await this.entries.save(from);await this.entries.save(to);await this.event(from,"TRANSFERRED",input.actorUserId,{toEntryId:to.id,branchId:to.branchId,serviceId:to.serviceId});await this.event(to,"CHECKED_IN",input.actorUserId,{transferFromEntryId:from.id});return{from,to}; }
  eventsAfter(tenantId:string,afterSequence:number,options?:{branchId?:string;serviceId?:string;limit?:number}){return this.events.listAfter(tenantId,afterSequence,options);}
  eventsForEntry(tenantId:string,entryId:string){return this.events.listForEntry(tenantId,entryId);}
  private async createEntry(input:{tenantId:string;branchId:string;serviceId:string;departmentId?:string|null;config:QueueConfiguration;kind:"WALK_IN"|"APPOINTMENT";appointmentId:string|null;customer:QueueCustomerReference;priority?:QueuePriority;priorityAdjustment?:number;source?:QueueCheckInSource;idempotencyKey?:string|null;metadata?:Record<string,unknown>;actorUserId?:string|null}) { const priority=input.priority??"STANDARD";const adjustment=input.priorityAdjustment??0; if(!Number.isInteger(adjustment)||adjustment<-99||adjustment>99)throw new QueueValidationError("Priority adjustment must be an integer between -99 and 99"); const now=new Date(); const ticket=await this.entries.nextTicketNumber(input.tenantId,input.branchId,input.serviceId,input.config.prefix,this.businessDate(now)); const item=new QueueEntry({id:randomUUID(),tenantId:input.tenantId,publicToken:randomUUID(),ticketNumber:ticket,kind:input.kind,branchId:input.branchId,serviceId:input.serviceId,departmentId:input.departmentId??null,appointmentId:input.appointmentId,customer:input.customer,priority,priorityAdjustment:adjustment,priorityScore:QueueEntry.score(priority,adjustment),checkInSource:input.source??"PUBLIC",status:"WAITING",stationId:null,servingStaffUserId:null,recallCount:0,checkedInAt:now,calledAt:null,serviceStartedAt:null,completedAt:null,noShowAt:null,cancelledAt:null,transferredAt:null,idempotencyKey:input.idempotencyKey?.trim()||null,transferFromEntryId:null,metadata:input.metadata??{},createdAt:now,updatedAt:now}); await this.entries.save(item);await this.event(item,"CHECKED_IN",input.actorUserId??null,{kind:item.kind,ticketNumber:item.ticketNumber});await this.audit("queue.checked_in",item.tenantId,input.actorUserId??null,"queue_entry",item.id,{ticketNumber:item.ticketNumber,branchId:item.branchId,serviceId:item.serviceId});return item; }
  private async requireQueueConfiguration(tenantId:string,branchId:string,serviceId:string,departmentId?:string|null){const config=await this.configurations.findForQueue(tenantId,branchId,serviceId,departmentId??null);if(!config)throw new QueueConfigurationNotFoundError(branchId,serviceId);return config;}
  private async requireConfiguration(tenantId:string,id:string){const config=await this.configurations.findById(tenantId,id);if(!config)throw new QueueConfigurationNotFoundError(id,id);return config;}
  private async requireEntry(tenantId:string,id:string){const item=await this.entries.findById(tenantId,id);if(!item)throw new QueueEntryNotFoundError(id);return item;}
  private async event(item:QueueEntry,type:QueueEventType,actorUserId:string|null,data:Record<string,unknown>){return this.events.append({id:randomUUID(),tenantId:item.tenantId,branchId:item.branchId,serviceId:item.serviceId,entryId:item.id,type,actorUserId,data,createdAt:new Date()});}
  private businessDate(value:Date){return value.toISOString().slice(0,10);}
  private validation(error:unknown){return new QueueValidationError(error instanceof Error?error.message:"Invalid queue operation");}
  private state(error:unknown){return new QueueStateError(error instanceof Error?error.message:"Invalid queue state transition");}
  private async audit(action:string,tenantId:string,actorUserId:string|null,targetType:string,targetId:string,metadata:Record<string,unknown>){if(!this.auditLog)return;await this.auditLog.record({tenantId,actorUserId,action,targetType,targetId,metadata});}
}
