import { CalendarPlus, CheckCircle2, Clock3, MoreHorizontal, Search, UserCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { klerionApi, type ApiAppointment } from "../lib/api";
import type { KlerionSession } from "../lib/session";

const preview: ApiAppointment[] = [
  { id:"APT-1048",tenantId:"demo",customerEmail:"adeola@example.com",serviceName:"Account opening",startAt:new Date().toISOString(),endAt:new Date(Date.now()+1800000).toISOString(),status:"booked",createdAt:new Date().toISOString() },
  { id:"APT-1047",tenantId:"demo",customerEmail:"chidi@example.com",serviceName:"Document verification",startAt:new Date(Date.now()+3600000).toISOString(),endAt:new Date(Date.now()+5400000).toISOString(),status:"checked_in",createdAt:new Date().toISOString() },
  { id:"APT-1046",tenantId:"demo",customerEmail:"fatima@example.com",serviceName:"Loan inquiry",startAt:new Date(Date.now()+7200000).toISOString(),endAt:new Date(Date.now()+9000000).toISOString(),status:"completed",createdAt:new Date().toISOString() },
];

export function AppointmentsView({ session }: { readonly session: KlerionSession }) {
  const [items,setItems]=useState<ApiAppointment[]>(preview); const [loading,setLoading]=useState(session.mode==="live"); const [notice,setNotice]=useState("");
  useEffect(()=>{if(session.mode!=="live")return; void klerionApi.listAppointments(session).then((data)=>setItems(data.length?data:preview)).catch((error)=>setNotice(error instanceof Error?error.message:"Unable to load appointments")).finally(()=>setLoading(false));},[session]);
  async function transition(item:ApiAppointment,action:"check-in"|"complete"){if(session.mode!=="live"){setItems(current=>current.map(row=>row.id===item.id?{...row,status:action==="check-in"?"checked_in":"completed"}:row));return;}try{const updated=action==="check-in"?await klerionApi.checkInAppointment(session,item.id):await klerionApi.completeAppointment(session,item.id);setItems(current=>current.map(row=>row.id===item.id?updated:row));}catch(error){setNotice(error instanceof Error?error.message:"Action failed");}}
  return <section className="view"><header className="view-heading"><div><span className="eyebrow">Service operations</span><h1>Appointments</h1><p>Manage bookings from confirmation through check-in and completion.</p></div><button className="primary"><CalendarPlus size={16} />New appointment</button></header>{notice&&<div className="inline-alert">{notice}</div>}<div className="toolbar"><label><Search size={16}/><input placeholder="Search customer or service" /></label><select><option>All statuses</option><option>Booked</option><option>Checked in</option><option>Completed</option></select><select><option>All branches</option><option>Victoria Island</option></select></div><article className="panel table-panel"><table><thead><tr><th>Customer</th><th>Service</th><th>Schedule</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Loading appointments…</td></tr>:items.map(item=><tr key={item.id}><td><div className="identity-cell"><span>{item.customerEmail[0]?.toUpperCase()}</span><div><strong>{item.customerEmail}</strong><small>{item.id}</small></div></div></td><td>{item.serviceName}</td><td><div className="stack"><strong>{new Date(item.startAt).toLocaleDateString()}</strong><small><Clock3 size={13}/>{new Date(item.startAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</small></div></td><td><span className={`status ${item.status}`}>{item.status.replace("_"," ")}</span></td><td><div className="row-actions">{item.status==="booked"&&<button onClick={()=>transition(item,"check-in")}><UserCheck size={15}/>Check in</button>}{item.status==="checked_in"&&<button onClick={()=>transition(item,"complete")}><CheckCircle2 size={15}/>Complete</button>}<button className="icon-button"><MoreHorizontal size={17}/></button></div></td></tr>)}</tbody></table></article></section>;
}
