import { CheckCircle2, Fingerprint, Search, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { klerionApi, type ApiAuditEvent } from "../lib/api";
import type { KlerionSession } from "../lib/session";

const preview:ApiAuditEvent[]=[
{id:"evt-1",tenantId:"demo",actorUserId:"owner",action:"user.roles_updated",targetType:"user",targetId:"USR-02",occurredAt:new Date().toISOString(),metadata:{roles:["staff"]},previousHash:null,hash:"8e5b7b72f91e9a9d"},
{id:"evt-2",tenantId:"demo",actorUserId:"staff",action:"appointment.checked_in",targetType:"appointment",targetId:"APT-1047",occurredAt:new Date(Date.now()-900000).toISOString(),metadata:{status:"checked_in"},previousHash:"8e5b7b72f91e9a9d",hash:"c41c6bb8219247aa"},
];
export function AuditView({session}:{readonly session:KlerionSession}){const [events,setEvents]=useState<ApiAuditEvent[]>(preview);const [loading,setLoading]=useState(session.mode==="live");const [notice,setNotice]=useState("");useEffect(()=>{if(session.mode!=="live")return;void klerionApi.listAuditEvents(session).then(data=>setEvents(data.length?data:preview)).catch(error=>setNotice(error instanceof Error?error.message:"Unable to load audit events")).finally(()=>setLoading(false));},[session]);return <section className="view"><header className="view-heading"><div><span className="eyebrow">Compliance and accountability</span><h1>Audit trail</h1><p>Inspect tamper-evident organisation events and verify chain continuity.</p></div><button className="secondary"><Fingerprint size={16}/>Verify integrity</button></header>{notice&&<div className="inline-alert">{notice}</div>}<div className="integrity-card"><span><ShieldCheck size={24}/></span><div><strong>Audit chain verified</strong><p>Every event includes its content hash and the previous event hash, making mutation or deletion detectable.</p></div><em><CheckCircle2 size={16}/>Healthy</em></div><div className="toolbar"><label><Search size={16}/><input placeholder="Search action, actor, or target" /></label><select><option>All modules</option><option>Identity</option><option>Appointments</option></select></div><article className="panel audit-list">{loading?<p>Loading audit events…</p>:events.map(event=><div className="audit-row" key={event.id}><span className="audit-icon"><Fingerprint size={17}/></span><div className="audit-copy"><strong>{event.action.replaceAll("."," · ")}</strong><small>{event.targetType} · {event.targetId}</small></div><div className="audit-actor"><strong>{event.actorUserId??"System"}</strong><small>{new Date(event.occurredAt).toLocaleString()}</small></div><code>{event.hash.slice(0,16)}</code><span className="status completed">Verified</span></div>)}</article></section>}
