import { ArrowRight, Building2, CheckCircle2, MapPin, Users } from "lucide-react";
import { useState } from "react";
import { Brand } from "../components/Brand";

const steps = ["Organisation", "Operations", "Team", "Complete"];
export function OnboardingView({ onComplete }: { readonly onComplete: () => void }) {
  const [step, setStep] = useState(0);
  return <main className="onboarding"><header><Brand /><span>Workspace setup</span></header><div className="onboarding-wrap"><aside>{steps.map((label, index) => <div className={index <= step ? "active" : ""} key={label}><i>{index < step ? <CheckCircle2 size={15} /> : index + 1}</i><span>{label}</span></div>)}</aside><section className="setup-card">{step === 0 && <><span className="setup-icon"><Building2 /></span><h1>Tell us about your organisation</h1><p>This configures localisation, working hours, and recommended modules.</p><div className="form-grid"><label>Industry<select defaultValue="financial"><option value="financial">Financial services</option><option>Professional services</option><option>Healthcare</option><option>Government</option></select></label><label>Company size<select><option>1–20 employees</option><option>21–100 employees</option><option>101–500 employees</option><option>500+ employees</option></select></label><label>Country<input defaultValue="Nigeria" /></label><label>Timezone<input defaultValue="Africa/Lagos" /></label></div></>}{step === 1 && <><span className="setup-icon"><MapPin /></span><h1>Set the operating structure</h1><p>Start with one branch. More locations and departments can be added later.</p><div className="form-grid"><label>Primary branch<input placeholder="Victoria Island HQ" /></label><label>City<input placeholder="Lagos" /></label><label>Opening time<input type="time" defaultValue="08:00" /></label><label>Closing time<input type="time" defaultValue="17:00" /></label></div></>}{step === 2 && <><span className="setup-icon"><Users /></span><h1>Invite the first administrators</h1><p>Invitations will become active when the invite service is implemented.</p><label>Team emails<textarea placeholder="operations@company.com&#10;hr@company.com" /></label></>}{step === 3 && <><span className="setup-icon success"><CheckCircle2 /></span><h1>Your workspace foundation is ready</h1><p>You can now explore the company console and continue configuring services, branches, and roles.</p><div className="completion-list"><div><CheckCircle2 />Organisation settings established</div><div><CheckCircle2 />Primary location prepared</div><div><CheckCircle2 />Owner access confirmed</div></div></>}<footer><button className="secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>Back</button><button className="primary" onClick={() => step === steps.length - 1 ? onComplete() : setStep(step + 1)}>{step === steps.length - 1 ? "Open Klerion" : "Continue"}<ArrowRight size={16} /></button></footer></section></div></main>;
}
