import { MoreHorizontal, Search, ShieldCheck, UserPlus } from "lucide-react";
import { useEffect, useState } from "react";
import { klerionApi, type ApiUser } from "../lib/api";
import type { KlerionSession } from "../lib/session";

const preview: ApiUser[]=[
{id:"USR-01",email:"owner@klerion.demo",roles:["owner"],createdAt:new Date().toISOString()},
{id:"USR-02",email:"operations@klerion.demo",roles:["staff"],createdAt:new Date().toISOString()},
{id:"USR-03",email:"member@klerion.demo",roles:["member"],createdAt:new Date().toISOString()},
];
export function UsersView({session}:{readonly session:KlerionSession}){const [users,setUsers]=useState<ApiUser[]>(preview);const [loading,setLoading]=useState(session.mode==="live");const [notice,setNotice]=useState("");useEffect(()=>{if(session.mode!=="live")return;void klerionApi.listUsers(session).then(setUsers).catch(error=>setNotice(error instanceof Error?error.message:"Unable to load users")).finally(()=>setLoading(false));},[session]);async function changeRole(user:ApiUser,role:string){try{if(session.mode==="demo"){setUsers(current=>current.map(item=>item.id===user.id?{...item,roles:[role]}:item));return;}const updated=await klerionApi.updateUserRoles(session,user.id,[role]);setUsers(current=>current.map(item=>item.id===user.id?updated:item));}catch(error){setNotice(error instanceof Error?error.message:"Role update failed");}}
return <section className="view"><header className="view-heading"><div><span className="eyebrow">Identity and access</span><h1>Users & roles</h1><p>Control tenant membership and administrative permissions.</p></div><button className="primary"><UserPlus size={16}/>Invite user</button></header>{notice&&<div className="inline-alert">{notice}</div>}<div className="security-summary"><ShieldCheck size={20}/><div><strong>Role changes are protected and auditable</strong><span>Klerion prevents removal of the final owner and records every update in the hash-chained audit trail.</span></div></div><div className="toolbar"><label><Search size={16}/><input placeholder="Search people" /></label><select><option>All roles</option><option>Owner</option><option>Staff</option><option>Member</option></select></div><article className="panel table-panel"><table><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Security</th><th /></tr></thead><tbody>{loading?<tr><td colSpan={5}>Loading users…</td></tr>:users.map(user=><tr key={user.id}><td><div className="identity-cell"><span>{user.email[0]?.toUpperCase()}</span><div><strong>{user.email}</strong><small>{user.id}</small></div></div></td><td><select className="role-select" value={user.roles[0]??"member"} onChange={event=>void changeRole(user,event.target.value)}><option value="owner">Owner</option><option value="staff">Staff</option><option value="member">Member</option></select></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td><span className="status completed">Protected</span></td><td><button className="icon-button"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></article></section>}
